version: '3'

services:
  microservice1:
    image: jhimyj/api-resenias1:latest
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=52.200.211.135
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_DIALECT=postgres

  microservice2:
    image: jhimyj/api-productos
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@52.200.211.135:3306/mydb

  microservice3:
    image: jhimyj/api-pedidos:latest
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    environment:
      - MONGODB_URI=mongodb://172.31.38.207/mydb

  orchestrator:
    image: jhimyj/orquestadora:latest
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    environment:
      - PRODUCTOS_SERVICE_URL=http://microservice2:8000
      - PEDIDOS_SERVICE_URL=http://microservice3:8080
      - RESENIAS_SERVICE_URL=http://microservice1:3000
    depends_on:
      - microservice1
      - microservice2
      - microservice3
    command: ["./wait-for-it.sh", "microservice1:3000", "--", "./wait-for-it.sh", "microservice2:8000", "--", "./wait-for-it.sh", "microservice3:8080", "--", "npm", "start"]

networks:
  mynetwork:
    driver: bridge
