version: '3'

services:
  microservice1:
    image: jhimyj/api-resenia:latest
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_HOST=52.200.211.135
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_DIALECT=postgres

  microservice2:
    image: jhimyj/api-productos:latest
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      - DATABASE_URL=mysql+pymysql://root:utec@52.200.211.135:3306/mydb

  microservice3:
    image: jhimyj/api-pedidos:latest
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    environment:
      - MONGODB_URI=mongodb://user:password@52.200.211.135:27017/mydb

  orchestrator:
    image: jhimyj/api-orquestadora:latest
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    environment:
      - PRODUCTOS_SERVICE_URL=http://microservice2:8000
      - PEDIDOS_SERVICE_URL=http://microservice3:8080
      - RESENIAS_SERVICE_URL=http://microservice1:3000

networks:
  mynetwork:
    driver: bridge
